// Mocks generated by Mockito 5.0.15 from annotations
// in practice_riverpod/test/hotpepper_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:practice_riverpod/core/domain/entity/hotpepper.dart' as _i4;
import 'package:practice_riverpod/core/gateway/datasource/hotpepper_datasource.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [HotPepperDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotPepperDatasource extends _i1.Mock
    implements _i2.HotPepperDatasource {
  MockHotPepperDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.HotPepper>> fetchRepositories({String? searchText}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchRepositories, [], {#searchText: searchText}),
          returnValue:
              Future<List<_i4.HotPepper>>.value(<_i4.HotPepper>[])) as _i3
          .Future<List<_i4.HotPepper>>);
  @override
  String toString() => super.toString();
}
